<!DOCTYPE HTML>
<html<?php $this->render('html-attrs', '');?>>
<head<?php $this->render('head-attrs', '');?>>
<?php 
	$this->render('head-base','');
	$this->renderEOL();
	$this->render('head-title',''); 
	$this->renderEOL();
	$this->render('head-meta', '', PHP_EOL);
	$this->renderEOL();
	$this->render('head-css',  '', '');?>
</head>
<body<?php $this->render('body-attrs', ''); ?>>
<?php $this->render('body-markup', ''); ?>
<?php $this->render('body-js', '', '');?>
</body>
</html>
