<!DOCTYPE HTML>
<html>
<head>
<?php 
	$this->render('html-head-title', '<title>Appfuel Default Title</title>');
	$this->render('html-head-base', '');

	$this->renderList('html-head-links', '');
	$this->renderList('html-head-meta', '');

	$this->render('html-head-style', '');
	$this->render('html-head-script', '');
?>
</head>
<body <?php $this->render('html-body-attrs', ''); ?>>
	<?php 
		$this->render('html-body-content', ''); 
		
		$this->renderList('html-body-scripts', '');
		$this->render('html-body-inline-script', '');
	?>
</body>
</html>
