<!DOCTYPE HTML>
<html>
<head>
<?php 
	$this->render('html-head-title', '');
	$this->render('html-head-base', '');
	
	$this->render('html-head-charset', '');
	$this->render('html-head-meta', '');

	$this->render('html-head-scripts', '');
	$this->render('html-head-links', '');

	$this->render('html-head-inline-style', '');
	$this->render('html-head-inline-script', '');
?>

</head>
<body<?php $this->render('html-body-attrs', ''); ?>>
<?php 
	$this->render('html-body-grid', ''); 		
	$this->render('html-body-scripts', '');
	$this->render('html-body-inline-script', '');?>
</body>
</html>
