<?php $this->render('doc-type', '<!DOCTYPE HTML>'); ?>

<html<?php $this->render('html-attr-string', '');?>>
<head<?php $this->render('head-attr-string', '');?>>
<?php
    $this->render('html-charset','');
    $this->render('html-base','');
    $this->render('html-title','');
	$this->render('html-meta', '',PHP_EOL);

	$isCss = $this->get('is-css', true);
	$isCss = ($isCss === false) ? false : true;
	if ($isCss) {
		$this->render('links-css',  '', PHP_EOL);
		$this->render('inline-css', '');
	}

	$isJs = $this->get('is-js', true);
	$isJs = ($isJs === false) ? false : true;
    if ($isJs) {
		$this->render('scripts-js-head', '', PHP_EOL);
		$this->render('inline-js-head', '');
	} 
?>

</head>
<body<?php $this->render('body-attr-string', ''); ?>>
<?php 
	$this->render('body-content', '');
	if ($isJs) {
		$this->render('scripts-js-body', '', '');
		$this->render('inline-js-body', '');
	}

	$this->render('body-content-final', PHP_EOL);
?>
</body>
</html>
